In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
test_data = pd.read_csv('./data_test.csv')
train_data = pd.read_csv('./data_train.csv')

In [6]:
train_data

shot_isGoal shot_bodyPart  location_X  location_Y
0               1    right_foot          80          32
1               1     left_foot          92          40
2               1     left_foot          96          45
3               1     left_foot          91          43
4               1    right_foot          92          45
...           ...           ...         ...         ...
1791            0    right_foot          83          33
1792            0    right_foot          87          40
1793            0    right_foot          71          68
1794            0    right_foot          93          37
1795            0    right_foot          95          56

[1796 rows x 4 columns]

In [7]:
train_data['shot_bodyPart'] = train_data['shot_bodyPart'].str.replace('right_foot','1')
train_data['shot_bodyPart'] = train_data['shot_bodyPart'].str.replace('left_foot','2')
train_data['shot_bodyPart'] = train_data['shot_bodyPart'].str.replace('head_or_other','3')

In [8]:
test_data['shot_bodyPart'] = test_data['shot_bodyPart'].str.replace('right_foot','1')
test_data['shot_bodyPart'] = test_data['shot_bodyPart'].str.replace('left_foot','2')
test_data['shot_bodyPart'] = test_data['shot_bodyPart'].str.replace('head_or_other','3')

In [9]:
test_data['shot_isGoal'].value_counts()

0    688
1     81
Name: shot_isGoal, dtype: int64

In [10]:
train_data['shot_isGoal'].value_counts()

0    1606
1     190
Name: shot_isGoal, dtype: int64

In [11]:
y_test = test_data['shot_isGoal']
y_train = train_data['shot_isGoal']

In [12]:
x_test = test_data[['shot_bodyPart','location_X','location_Y']]
x_train = train_data[['shot_bodyPart','location_X','location_Y']]


In [13]:
from sklearn.linear_model import LogisticRegression


In [14]:
logmodel = LogisticRegression()


In [15]:
logmodel.fit(x_train, y_train)


LogisticRegression()

In [16]:
Predictions = logmodel.predict(x_test)


In [17]:
from sklearn.metrics import classification_report


In [18]:
print(classification_report(y_test,Predictions))


              precision    recall  f1-score   support

           0       0.89      1.00      0.94       688
           1       0.00      0.00      0.00        81

    accuracy                           0.89       769
   macro avg       0.45      0.50      0.47       769
weighted avg       0.80      0.89      0.84       769



/Users/jonasovergaard/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jonasovergaard/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jonasovergaard/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

In [19]:
from sklearn.metrics import confusion_matrix


In [20]:
confusion_matrix(y_test,Predictions)

array([[688,   0],
       [ 81,   0]])

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
dtree = DecisionTreeClassifier()

In [22]:
dtree.fit(x_train, y_train)

DecisionTreeClassifier()

In [23]:
predictions = dtree.predict(x_test) 

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

In [25]:
print(confusion_matrix(y_test,predictions))
print('')
print(classification_report(y_test,predictions))

[[652  36]
 [ 71  10]]

              precision    recall  f1-score   support

           0       0.90      0.95      0.92       688
           1       0.22      0.12      0.16        81

    accuracy                           0.86       769
   macro avg       0.56      0.54      0.54       769
weighted avg       0.83      0.86      0.84       769



In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rfc = RandomForestClassifier(n_estimators=300)

In [28]:
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=300)

In [29]:
rfc_pred = rfc.predict(x_test) 

In [30]:
print(confusion_matrix(y_test, rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[659  29]
 [ 68  13]]


              precision    recall  f1-score   support

           0       0.91      0.96      0.93       688
           1       0.31      0.16      0.21        81

    accuracy                           0.87       769
   macro avg       0.61      0.56      0.57       769
weighted avg       0.84      0.87      0.86       769

